"""empty message

Revision ID: 94cf85b0d9b8
Revises: 
Create Date: 2020-05-17 19:25:43.165119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cf85b0d9b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follow_ibfk_2', 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'login', ['source_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key('follow_ibfk_2', 'follow', 'users', ['source_user_id'], ['id'])
    # ### end Alembic commands ###
